update submit-bot-report node version to node20
Since this action does not use `isomorphic-unfetch` anymore, we get a
ReferenceError: fetch is not defined error
when running this action